import {sqliteTable,text,integer,real,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const researchAccounts=sqliteTable('research_accounts',{userId:text('user_id').primaryKey(),config:text('config').notNull(),revision:integer('revision').notNull().default(0)});
export const researchPositions=sqliteTable('research_positions',{id:text('id').primaryKey(),userId:text('user_id').notNull(),data:text('data').notNull(),closedAt:text('closed_at'),revision:integer('revision').notNull().default(0)});
export const researchEvents=sqliteTable('research_events',{id:text('id').primaryKey(),userId:text('user_id').notNull(),positionId:text('position_id').notNull(),kind:text('kind').notNull(),data:text('data').notNull(),createdAt:text('created_at').notNull()});
export const socialCache=sqliteTable('social_cache',{address:text('address').primaryKey(),data:text('data').notNull(),fetchedAt:integer('fetched_at').notNull()});
export const socialUsage=sqliteTable('social_usage',{id:text('id').primaryKey(),requests:integer('requests').notNull().default(0)});
export const researchLocks=sqliteTable('research_locks',{id:text('id').primaryKey(),owner:text('owner').notNull(),expires:integer('expires').notNull()});
// Goldmine signal tracking (lib/goldmine/signals.ts). Shared market observations: no user data.
export const goldmineSignals=sqliteTable('goldmine_signals',{id:text('id').primaryKey(),address:text('address').notNull(),pair:text('pair').notNull(),symbol:text('symbol').notNull(),modelVersion:text('model_version').notNull(),state:text('state').notNull(),score:integer('score').notNull(),opportunity:integer('opportunity').notNull(),detectedAt:integer('detected_at').notNull(),detectedPrice:real('detected_price').notNull(),snapshot:text('snapshot').notNull(),assessment:text('assessment').notNull()},table=>[index('goldmine_signals_detected_at_idx').on(table.detectedAt),index('goldmine_signals_pair_idx').on(table.pair,table.address)]);
export const goldmineOutcomes=sqliteTable('goldmine_outcomes',{signalId:text('signal_id').notNull(),horizon:text('horizon').notNull(),dueAt:integer('due_at').notNull(),deadlineAt:integer('deadline_at').notNull(),status:text('status').notNull().default('pending'),observedAt:integer('observed_at'),price:real('price'),liquidity:real('liquidity')},table=>[primaryKey({columns:[table.signalId,table.horizon]}),index('goldmine_outcomes_status_due_idx').on(table.status,table.dueAt)]);
