import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {reportFailure} from '@/lib/diagnostics';
import {db,getConfig,acquireLock,releaseLock,sameOrigin} from '@/lib/research-db';
import {socialSummary} from '@/lib/advisor';
import {readJsonObject} from '@/lib/request-body';
import {publicSocialEvidence,socialEvidenceMessage} from '@/lib/social-cache';
function token(){return (env as unknown as {X_BEARER_TOKEN?:string}).X_BEARER_TOKEN;}
export async function GET(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in required.'},{status:401});
 const address=new URL(request.url).searchParams.get('address');if(address&&!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(address))return Response.json({error:'Invalid contract.'},{status:400});
 try{const config=await getConfig(user.userId);const usage=await db().prepare('SELECT requests FROM social_usage WHERE id = ?').bind('x:'+user.userId+':'+new Date().toISOString().slice(0,10)).first<{requests:number}>();const cache=address?await db().prepare('SELECT data, fetched_at FROM social_cache WHERE address = ?').bind(address).first<{data:string;fetched_at:number}>():null;
 return Response.json({posts:[],...(cache?{...publicSocialEvidence(JSON.parse(cache.data)),cached:true,stale:Date.now()-cache.fetched_at>900000}:{}),message:token()?(cache?socialEvidenceMessage:'Research runs only when requested. Daily request cap applies.'):'Add X_BEARER_TOKEN as a secret in Site environment settings, then publish to activate. Never put the token in chat or client code.',configured:!!token(),status:token()?'connected':'not_connected',usedToday:usage?.requests||0,dailyLimit:config.xDailyRequests},{headers:{'Cache-Control':'no-store'}});
 }catch(e){reportFailure('social','load',e);return Response.json({status:'error',posts:[],message:'Social research storage unavailable.'},{status:503});}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in required.'},{status:401});if(!sameOrigin(request))return Response.json({error:'Same-origin request required.'},{status:403});const key=token();if(!key)return Response.json({status:'not_connected',posts:[],message:'X API secret is not configured.'},{status:409});
 const b:any=await readJsonObject(request);if(!b)return Response.json({error:'Invalid JSON body.'},{status:400});let lock:string|null=null;let lockId='';
 try{const address=String(b.address||'');if(!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(address))return Response.json({error:'Invalid Solana address.'},{status:400});
 lockId='social:'+address;lock=await acquireLock(lockId);if(!lock)return Response.json({status:'busy',posts:[],message:'This contract is already being researched. Try again shortly.'},{status:409});
 const config=await getConfig(user.userId);
 const usageId='x:'+user.userId+':'+new Date().toISOString().slice(0,10);
 const cache=await db().prepare('SELECT data, fetched_at FROM social_cache WHERE address = ?').bind(address).first<{data:string;fetched_at:number}>();if(cache&&Date.now()-cache.fetched_at<900000){const usage=await db().prepare('SELECT requests FROM social_usage WHERE id = ?').bind(usageId).first<{requests:number}>();return Response.json({...publicSocialEvidence(JSON.parse(cache.data)),status:'connected',configured:true,cached:true,stale:false,message:socialEvidenceMessage,usedToday:usage?.requests||0,dailyLimit:config.xDailyRequests},{headers:{'Cache-Control':'no-store'}});}
 if(config.xDailyRequests<=0)return Response.json({status:'limit_reached',posts:[],message:'X research is paused. Set a daily request cap in Advisor settings.'},{status:429});
 const reserved=await db().prepare('INSERT INTO social_usage (id, requests) VALUES (?, 1) ON CONFLICT(id) DO UPDATE SET requests = social_usage.requests + 1 WHERE social_usage.requests < ? RETURNING requests').bind(usageId,config.xDailyRequests).first<{requests:number}>();if(!reserved)return Response.json({status:'limit_reached',posts:[],message:'Daily X request cap reached. Cached evidence remains available.'},{status:429});
 const response=await fetch('https://api.x.com/2/tweets/search/recent?query='+encodeURIComponent(address+' -is:retweet')+'&max_results=25&tweet.fields=created_at,author_id,public_metrics',{headers:{Authorization:'Bearer '+key,Accept:'application/json'},signal:AbortSignal.timeout(12000)});
 if(!response.ok){reportFailure('social','x-search',new Error(`X returned ${response.status}`),'warn');return Response.json({status:'error',posts:[],message:`X returned ${response.status}. Check API access and credits. This attempt counts against the daily request cap.`},{status:502});}
 const raw:any=await response.json();if(raw.errors?.length&&!Array.isArray(raw.data))throw Error('X returned errors without data');const posts=Array.isArray(raw.data)?raw.data:[];
 const evidence=publicSocialEvidence({address,posts:posts.map((p:any)=>({text:String(p.text||''),date:p.created_at,url:'https://x.com/i/status/'+p.id,author:p.author_id})),summary:socialSummary(posts),asOf:new Date().toISOString()});
 await db().prepare('INSERT INTO social_cache (address, data, fetched_at) VALUES (?, ?, ?) ON CONFLICT(address) DO UPDATE SET data = excluded.data, fetched_at = excluded.fetched_at').bind(address,JSON.stringify(evidence),Date.now()).run();return Response.json({...evidence,status:'connected',configured:true,cached:false,stale:false,message:socialEvidenceMessage,usedToday:reserved.requests,dailyLimit:config.xDailyRequests},{headers:{'Cache-Control':'no-store'}});
 }catch(e){reportFailure('social','research',e);return Response.json({status:'error',posts:[],message:'X research failed. No social evidence was added.'},{status:503});}finally{if(lock)await releaseLock(lockId,lock).catch(e=>reportFailure('social','release-lock',e));}}
